project:
  type: website
  output-dir: docs

website:
  title: "Moshi Alam"
  # favicon: 
  navbar:
    pinned: true
    right:
      - href: index.qmd
        text: Research
      - teaching.qmd
      - cv.qmd
      - icon: github
        href: https://github.com/moshialam
      # - icon: twitter
      #   href: https://twitter.com/MoshiAlam
  page-footer:
      background: light
      left:
            - "Copyright 2021, Md Moshi Ul Alam. Website created using Quarto."
      # right:
format:
  html:
    theme: #flatly # cosmo 
      united
      # styles.scss
      # light: cosmo # flatly # simplex cosmo united
      # dark: darkly # solar
    css: styles.css
    mainfont: Palatino, "Palatino Linotype", "Book Antiqua", Georgia, serif
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
          <style>
            :root {
              --cream-bg: #FFFDF8;      /* Much lighter, almost white with hint of warmth */
              --dark-text: #3A3A3A;     /* Softer dark gray, not harsh black */
              --rust-link: #B8653A;     /* Warm rust/terracotta for links */
              --rust-hover: #A0522D;    /* Darker rust on hover */
              --nav-text: #8B5A3C;      /* Brown for navigation */
            }
            
            body {
              background-color: #FFFDF8 !important;  /* Very light cream */
              color: #3A3A3A !important;              /* Soft dark gray */
            }
            
            .navbar {
              background-color: #FFFDF8 !important;
              border-bottom: none !important;
              box-shadow: none !important;
              margin-bottom: 0 !important;
              padding-bottom: 0rem !important;
            }
            
            .navbar-brand, .navbar-nav .nav-link {
              color: #8B5A3C !important;    /* Warm brown */
              font-weight: 500;
              letter-spacing: 0.8px;
              text-transform: uppercase;
              font-size: 1.rem;
            }
            
            .navbar-nav .nav-link:hover {
              color: #B8653A !important;
              text-decoration: none;
            }
            
            /* Main content links */
            a {
              color: #A0522D;       /* Warm rust/terracotta */
              text-decoration: none;
            }
            
            a:hover {
              color: #8B4513;       /* Darker rust on hover */
              text-decoration: underline;
            }
            
            /* Headers */
            h1, h2, h3, h4, h5, h6 {
              color: #2C3E50;       /* Slightly darker for headers */
            }
            
            .page-footer {
              background-color: #FAF5F0 !important;  /* Slightly darker than body */
              border-top: 1px solid #F0E8DF;
              color: #6B5D54;
            }
            
            /* Make text more readable */
            p, li {
              color: #3A3A3A;
              line-height: 1.6;
            }
          </style>
    toc: true
    html-math-method: katex
    smooth-scroll: true
    link-external-icon: false
    page-layout: full
    code-fold: true
    # code-tools: true
    code-link: true
    # code-block-bg: true
    # code-block-border-left: "#31BAE9"
    include-before-body: _profile-header.html




