#### <i class="bi bi-bookmark-check"></i> Working papers
- [**Employee-Side Discrimination: Beliefs and Preferences**](papers/Alam_JMP_Oct21.pdf) (PhD JMP)  <p>with Mehreen Mookerjee and Sanket Roy **<a href="#" data-micromodal-trigger="abs_workerdisc" tabindex="0" class="text-info">
  [+Abstract]
</a>** <p class="text-info"> _R&R at Quantitative Economics_ </p> </p>
- [**Labor Market Consequences of Pay-Equity Laws**](papers/Alam_JMP_payequity.pdf) (Post-doc JMP) <p>with Steven Lehrer and Nuno Souso Pereira **<a href="#" data-micromodal-trigger="abs_payequity" tabindex="0" class="text-info">
  [+Abstract]
</a>** 
<p><span class="badge bg-primary">_Updated Dec '24_</span>  <small><small> [_Under review_] </small></small> </p> 
- [**The Unintended Benefits of Women’s Empowerment on Household Sanitation**](papers/Agarwal_Alam_sanitation.pdf) <p>with Monica Agarwal  **<a href="#" data-micromodal-trigger="abs_sanitation" tabindex="0" class="text-info">
  [+Abstract]
</a>** 
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4992568" class="text-info"> [<i class="fas fa-file-pdf" style="color: #ec0909;"></i> SSRN]</a> <p><span class="badge bg-primary">_Updated Dec '24_</span>  <small><small> [_Under review_] </small></small> </p>
---

#### <i class="bi bi-bookmark-check-fill"></i> Publications/Accepted 
- ["**Increases in shared custody after divorce in the United States.**"](https://www.demographic-research.org/volumes/vol46/38/default.htm) 
<p>with Daniel Meyer and Marcia Carlson. 
**<a href="#" data-micromodal-trigger="abs_divorce" tabindex="0" class="text-info">
  [+Abstract]
</a>** 
<a href="https://www.demographic-research.org/volumes/vol46/38/default.htm" class="text-info"> [{{< fa code >}} Replication]</a>
 <p class="text-info"> *Demographic Research* 46 (2022): 1137-1162. <a class="text-info"> *"Editor's Choice"* article</a></p> 

---

#### <i class="bi bi-bookmark"></i> Research in progress
- **Optimal Place-Based Redistribution**
<p> with Morris Davis and Jesse Gregory </p>
- **Spatial Inequality and School Choice Mechanisms**
<p> with Monica Agarwal, Chao Fu, YingHua He </p>
- **Labor Market Inequality and Collective Bargaining**
<p> with Steven Lehrer and Nuno Souso Pereira</p>
- **Racial Gaps in Wage Growth: Discrimination, Selection and Search Frictions**<p></p>

---

#### Dormant papers
- **Identification in Models of Discrimination** <p>[subsumed in my PhD job market paper "Employee Side Discrimination: Beliefs and Preferences"]</p>






























<!-- the rest of this stuff is for the popup! -->

```{ojs}
//| echo: false
//| include: false

micro = require("micromodal@0.4.10");

micro.init({
  awaitOpenAnimation: true,
  awaitCloseAnimation: true
});
```

<!-- abs_divorce -->

:::::: {#abs_divorce .modal .micromodal-slide aria-hidden="true"}
::::: {.modal__overlay tabindex="-1" data-micromodal-close="true"}
:::: {.modal__container role="dialog" aria-modal="true" aria-labelledby="abs_divorce-title"}

<button class="modal__close" aria-label="Close modal" data-micromodal-close></button>

<header>
#### Increases in shared custody after divorce in the United States {#abs_divorce-title}
</header>
::: {#modal-1-content}
This paper provides new evidence on the time trend in shared physical custody after divorce in the U.S., using eight waves of data from the Current Population Survey - Child Support Supplement. We find that the likelihood of shared custody more than doubled between divorces that occurred before 1985 and those in 2010-2014, from 12% to 28%. We show that non-Hispanic Whites and those who are more socioeconomically advantaged are more likely to have shared custody. Using more formal methods we show that the increase cannot be explained by changes in the characteristics of those divorcing; instead, we infer that this is the result of changing norms and policies that favor shared custody. Finally, this paper complements previous analyses using court record data from Wisconsin and shows that while the rate of shared custody in Wisconsin is higher than the national rate, a large increase over time has occurred in the nation as well as in Wisconsin. These changing patterns have important implications for children’s living arrangements and for the parental investments that children receive after their parents’ divorce.
:::

::::
:::::
::::::

<!-- abs_payequity -->

:::::: {#abs_payequity .modal .micromodal-slide aria-hidden="true"}
::::: {.modal__overlay tabindex="0" data-micromodal-close="true"}
:::: {.modal__container role="dialog" aria-modal="true" aria-labelledby="abs_payequity-title"}

<button class="modal__close" aria-label="Close modal" data-micromodal-close></button>

<header>
#### Labor Market Consequences of Pay-Equity Laws {#abs_payequity-title}
</header>
::: {#modal-1-content}
In 2018, Portugal enacted legislation to address gender wage gaps in the labor market. This legislation enforced pay equity laws on larger firms penalizing those with gaps exceeding five percent. Using rich administrative data which links employees to job-titles within firms, we analyze the law's impact both within and between genders using an event study design.  First, we document that there exists a distribution of gender wage gaps across jobs within firms. We show that in treated firms, jobs with initial gaps exceeding five percent saw a 12% reduction, through slower male wage growth, while jobs with gaps less than zero percent saw reduction in female wage growth to eliminate the gap. However, jobs with initial gaps in between zero and five percent saw an unintended consequence of the law where gender wage gaps increased by 66% (from 2.1% to 3.5%) mainly from decreased female wage growth. The unintended (intended) consequences are more pronounced in industries with above median share of male (female) workers. We find no evidence to suggest that firms changed their size to avoid the law, and we find precise null effects of the impact of the law on the gender composition of workers within jobs, and hours worked by workers. Our findings underscore how the establishment of a well-intentioned but uniform target gender wage gap clarified the repercussions for gender imbalances thereby leading to unintended consequences.
:::

::::
:::::
::::::



<!-- abs_workerdisc -->
:::::: {#abs_workerdisc .modal .micromodal-slide aria-hidden="true"}
::::: {.modal__overlay tabindex="0" data-micromodal-close="true"}
:::: {.modal__container role="dialog" aria-modal="true" aria-labelledby="abs_workerdisc-title"}

<button class="modal__close" aria-label="Close modal" data-micromodal-close></button>

<header>
#### Employee-Side Discrimination: Beliefs and Preferences {#abs_workerdisc-title}
</header>
::: {#modal-1-content}
Tight labor markets are associated with high costs of worker-turnover. In such settings, firms might put significant weight on whom workers want to work for, while deciding promotions. Should workers prefer not to work for female managers, it could lower the chances of females being promoted. In this paper, we present novel evidence on the distribution of workers' preferences regarding manager gender and their beliefs of managers' mentoring capabilities, which influence their job search and choice decisions. Using formal identification arguments in settings with varying information, we design an information experiment to separately identify worker beliefs from their preferences in a structural model. In the absence of information on manager quality, workers are indifferent to manager gender. However, upon receiving information on manager mentorship ability, workers prefer to work for female managers---as exhibited by their willingness to forgo 1.3--2.2% of average annual wages. Hence, absent additional information on mentorship skill, workers on average believe that female managers' mentoring ability is worse than male managers', with the magnitude of this evaluation corresponding to a wage differential of 1.6% of average annual wages. These averages mask rich heterogeneity. We find that 60% of workers prefer to work for female managers, and in the absence of information on mentorship ability, 62% believe male managers to be better mentors. An ex-post survey directly eliciting worker beliefs corroborates this finding. We find policy-relevant heterogeneity by maternal education level, parental employment status and worker major. Our results imply, the distribution of worker preferences could be used to test for discriminatory practices by the firm.
:::

::::
:::::
::::::




<!-- abs_sanitation -->
:::::: {#abs_sanitation .modal .micromodal-slide aria-hidden="true"}
::::: {.modal__overlay tabindex="0" data-micromodal-close="true"}
:::: {.modal__container role="dialog" aria-modal="true" aria-labelledby="abs_sanitation-title"}

<button class="modal__close" aria-label="Close modal" data-micromodal-close></button>

<header>
#### The Unintended Benefits of Women’s Empowerment on Household Sanitation {#abs_sanitation-title}
</header>
::: {#modal-1-content}
Existing research shows that women benefit more from private toilets, but misperceptions about the net benefits from toilets and lack of women's decision-making power can hinder toilet adoption by households. In this paper, we explore a novel link between household sanitation and policies that empower women. We show that a policy aimed at improving women's property inheritance rights in India led to an increase in toilet adoption in the households of treated cohorts by at least 10%. Prior literature shows mixed evidence on whether the policy increased women’s inheritance, but shows that the policy had significant indirect effects, such as improving women’s education. To generate empirical tests for the mechanisms driving our main results, we build a discrete choice model with idiosyncratic household preference shocks that produces  policy-relevant complementarity between women's education and decision-making power in adoption of a household public good valued more by women. Using a heterogeneity-robust event-study design, we find that, consistent with our model, the increase in toilet adoption is concentrated in states where the policy boosted women’s education—plausibly reducing misperceptions about the benefits of toilets—and increased women’s decision-making power. Our findings highlight that policies empowering women can yield unintended benefits beyond their original scope---while we document improvements in toilet coverage, the implications extend to other household investments where women's preferences are stronger, but various frictions limit adoption.
:::

::::
:::::
::::::









<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
