---
title: "Teaching"
---
<!-- 
### [Clark University](https://www.clarku.edu/departments/economics/) 

- Undergraduate: Introductory Econometrics
- Undergraduate: Applied Econometrics -->



### [Clark University](https://www.clarku.edu/departments/economics/) 

- [Undergraduate: Econometrics](/morepages/UG_intro_metrics.qmd)
- [PhD: Applied Econometrics-I: Causality & Design-Based Inference](/morepages/phddesignbased.qmd)
- [PhD: Applied Econometrics-II: Structural + Computation](/morepages/phdstructural.qmd)
- [PhD: Econometric Theory](/morepages/phdmetrics.qmd)
- Undergraduate: Statistics [ [Canvas Course Website] ](https://canvas.clarku.edu/courses/13122)

---

### [Queen's University](https://www.econ.queensu.ca/) 

- PhD: Structural and reduced form methods in labor economics
    - [ [Course Outline] ](/morepages/econ852.qmd)
- Undergraduate: Applied Econometrics: Causal Inference.
    - [ [Course Outline] ](/morepages/econ452.qmd) [ [Course Website] ](https://onq.queensu.ca/d2l/home/764511)

---

### [University of Wisconsin-Madison](https://econ.wisc.edu/) 
 <p class="text-info">  _Department of Economics Nominee for UW-Madison Letters & Sciences Teaching Fellows Award 2019_ </p>
 
- Econ 705 -- Econometric Theory (Graduate). _Instructors: [Jack Porter](https://www.ssc.wisc.edu/~jrporter/) & [Jeffrey Smith](https://sites.google.com/site/econjeffsmith/home)_ 
  - _Juli Plant Grainger Teaching Excellence Award_ 
  -  _Distinguished Teaching Assistant_

- Econ 706 -- Applied Econometrics (Graduate). _Instructors: [Christopher Taber](https://www.ssc.wisc.edu/~ctaber/) & [Kenneth West](https://www.ssc.wisc.edu/~kwest/)_
   - _Distinguished Teaching Assistant_

- Econ 101 [Head TA]. _Instructor: [Korinna Hansen](https://www.ssc.wisc.edu/~kohansen/); [Elizabeth Kelly](https://econ.wisc.edu/staff/kelly-elizabeth/); [Gwen Eudey](https://econ.wisc.edu/staff/eudey-gwen/) _
  - _Distinguished Teaching Assistant (x 2)_ 

<!-- - Econ 101. _Instructor: [Elizabeth Kelly](https://econ.wisc.edu/staff/kelly-elizabeth/)_ -->

<!-- - Econ 101. _Instructor: [Gwen Eudey](https://econ.wisc.edu/staff/eudey-gwen/)_ -->


---

### Resources for students

[Coding for undergrads](/morepages/resourcesforugstudents.qmd)

[Podcasts discussing empircal research in economics](/morepages/podcasts.qmd)
