---
title: "Code"
date-modified: last-modified
---

# Code for research

Here are the codes of some `julia` functions that I have implemented for some of my research. Some of them can easily be done in other languages through off-the-shelf packages. This is not to claim that `julia` code will be the most efficient but often it could help if the data or the parameter space is large. And I like coding in it. 

I have tried to make them context agnostic. However, they may not be fully general, some almost by construction. Hence these are not packages. Please feel free to use them, or report a bug if you find one!

- Parametric Empirical Bayes 
- Non-parametric Empirical Bayes with or without shape restrictions
- Nelder-Mead simplex algorithm
- Indirect Inference
- Event studies with interacted FE
- Quantile regressions with FE (Canay 2011)


# Code for teaching

Most of these are in `R`. Their objective is to primarily simulate data with failures in assumptions required for identification, or for inference and show what happens. Some of them are simply hard-coding the estimator instead of using a package which could help students remember and thus compare various estimators.

- Simple linear regression
- Central Limit Theorem
- Frisch-Waugh-Lovell theorem
<!-- - Random assignment with covariates -->
- IV and 2SLS
- Weak IV vs Strong IV