---
title: "Structural and reduced form methods in labor economics: Course Outline"
---

### Outline

- Principles of empirical research 
    - Identification
        - "Non-parametric identification", Matzkin (2007)
        - "Identification of models of the labor market" Taber and French (2010)
        - "Partial Identification in Econometrics" Tamer (2010)
    - Advantages of reduced form methods and advantages of structural models
    - Feasibility of each approach individually and jointly
    - "Structural Equations, Treatment Effects and Econometric Policy Evaluation" Heckman and Vytlacil (2003)
- Reduced form methods
    - Shift-share exclusion restrictions
        - "Bartik Instruments: What, When, Why and How" Goldsmith-Pinkham, Sorkin and Swift (2020)
        - "Quasi-experimental shift-share research designs" Borusyak, Hull and Jaravel (2020)
    - Variation in treatment timings and heterogenous effects
        - "What's trending in difference-in-differences?" Roth and Santa'Anna (2022)
        - "Two-way fixed effects estimators with heterogeneous treatment effects" de Chaisemartin and d`Haultfoeuille (2020)
        - "Inheritance rights and household sanitation" Alam and Agarwal (2023) 
    - Empirical Bayes
        - "Empirical Bayes deconvolution estimates." Efron (2016)
        - "Systemic discrimination among large US employers", Kline, Rose and Walters (2022)
        - "Robust empirical bayes confidence intervals" Armstrong, Kolesár and Plagborg-Møller (2022) 
    - Discontinuity based designs
        - "Inference on causal effects in a generalized regression kink design" Card et al. (2015)
        - "Inference in Regression Discontinuity Designs with a Discrete Running Variable", Kolesar and Rothe (2018)
- Structural models 
    - Conditional choice probabilities, discrete choice and dynamic models
        - "Conditional Choice Probabilities and the Estimation of Dynamic Models", Hotz and Miller (1993)
        - "College Attrition and the Dynamics of Information Revelation", Arcidiacono, Aucejo, Maurel, et al. (2018)
        - "Discrete Choice Methods with Simulation" Train (2009)
        - "The Structural Estimation of Behavioral Models: Discrete Choice Dynamic Programming Methods and Applications," Keane and Wolpin (2011)
    - Stated preference
        - "Preference for the workplace, investment in human capital and gender", Wiswall Zafar (2018)
        - "Optimal Place-based redistribution" Alam, Davis and Gregory (2023)  
        - "Understanding Migration Aversion Using Elicited Choice Probabilities", Kosar, Ransom, van der Klaauw (2022)
    - Models on wage inequality
        - "High wage workers and high wage firms" Abowd, Kramarz and Margolis (1999)
        - "A Distributional Framework for Matched Employer-employee data", Bonhomme, Lamadon, Manresa (2019)
        - "Racial Gaps in Wage Growth: Discrimination and Search Frictions" Alam (2020) 
        - "Discretizing Unobserved heterogeneity" Bonhomme, Lamadon, Manresa (2019)
        - "Monopsony in Movers: The Elasticity of Labor Supply to Firm Wage Policies", Bassier, Dube, Naidu (2021)
- Using both reduced form and structural models 
    - "Worker-side discrimination--Beliefs and Preferences - Evidence from an Information Experiment on Jobseekers", Alam, Mookerjee, Roy (2022) 
    - "Estimating Equilibrium Effects of Job Search Assistance," Gautier, Muller, van der Klaauw, Rosholm and Svarer (2018)
    - "The Demand for Food of Poor Urban Mexican Households: Understanding Policy Impacts Using Structural Models" Angelucci and Attanasio (2013)
    - "Evaluating Search and Matching Models Using Experimental Data" Lise, Seitz and Smith (2015)
    - "Evaluating a Structural Model of Labor Supply and Welfare Participation: Evidence from State Welfare Reform Experiments," Choi (2018)
    - "Estimating labour supply responses and welfare participation: Using a natural experiment to validate a structural labour supply model" Hansen and Liu (2015)
    - "The Role of Labor and Marriage Markets, Preference Heterogeneity and the Welfare System on the Life Cycle Decisions of Black, Hispanic and White Women," Keane and Wolpin (2010)
    - "Approximating the Equilibrium Effects of Informed School Choice," Allende, Gallego and Nielson (2019)
- Coding in Julia (if time permits)
    - Why Julia?
    - Efficient code, version control and large project workflow
    - Automatic testing and reproducibility
    - Introduction to numerical optimization

