---
title: "PhD: Causality & Design-Based Methods"
author: "Moshi Alam"
date: "2025"
format:
  html:
    toc: true
    toc-depth: 3
  #pdf:
    #toc: true
    #documentclass: article
---

## Course Description

This is the first course in a two-course sequence on applied econometrics at the PhD level, where we will cover design based methods for causal inference. The next course will cover model-based structural methods. 

There is no particular textbook for this course. We will mostly talk about the econometrics of methods and applications through papers. I will upload [slides on canvas](https://canvas.clarku.edu/courses/17807). 


## Course outline

- Potential outcomes framework
- Randomized controlled trials
- IV and Heterogeneous treatment effects
- Regression discontinuity designs
- FE, TWFE and Negative weights 
- Heterogeneity robust D-i-D and extensions
- Shrinkage Estimators
- Leniency IV Designs
- Shift share IV
- Marginal Treatment Effects


## Readings

This reading list by no means is exhaustive. I have tried to add handbook chapters and survey papers since they are pretty well explanatory. Your objective in reading these papers is not only to understand the empirical application but also to understand how good authors write and structure their papers.


- **Randomized Controlled Trials**
    - Miguel & Kremer (2004), "Worms: Identifying Impacts on Education and Health in the Presence of Treatment Externalities". Econometrica
    - Bertrand & Mullainathan (2004). "Are Emily and Greg more employable than Lakisha and Jamal? A field experiment on labor market discrimination." American Economic Review
    - Duflo, Glennerster, & Kremer, M. (2007), "Using Randomization in Development Economics Research: A Toolkit," Handbook of Development Economics.

- **Instrumental Variables and heterogeneous treatment effects**
    - Angrist & Krueger  (1991), "Does Compulsory School Attendance Affect Schooling and Earnings?" QJE.
    - Bound, Jaeger & Baker (1995), "Problems with Instrumental Variables Estimation when the Correlation between the Instruments and the Endogenous Explanatory Variable is Weak," Journal of the American Statistical Association.
    - Card (1999), "The Causal Effect of Education on Earnings," in Handbook of Labor Economics.
    - Imbens & Angrist, J. D. (1994), "Identification and Estimation of Local Average Treatment Effects," Econometrica.

- **Regression Discontinuity**
    - Lee  & Lemieux (2010), "Regression Discontinuity Designs in Economics," JEL
    - Black (1999). "Do Better Schools Matter? Parental Valuation of Elementary Education." Quarterly Journal of Economics
    - Zimmerman (2014). "The returns to college admission for academically marginal students." Journal of Labor Economics
    - Clark & Martorell (2014). "The signaling value of a high school diploma." Journal of Political Economy
    - Kolesar & Rothe (2018). "Inference in Regression Discontinuity Designs with a Discrete Running Variable." American Economic Review.

- **TWFE and Negative weights**
    - Goodman-Bacon (2021). "Difference-in-differences with variation in treatment timing." Journal of Econometrics.
    - de Chaisemartin & D'Haultfoeuille (2020). "Two-way fixed effects estimators with heterogeneous treatment effects." American Economic Review.

- **Heterogeneity robust D-i-D and extensions**
    - Callaway & Sant'Anna  (2021). "Difference-in-differences with multiple time periods." Journal of Econometrics.
    - Sun & Abraham (2021). "Estimating dynamic treatment effects in event studies with heterogeneous treatment effects." Journal of Econometrics.
    - Rambachan & Roth (2023) "A More Credible Approach to Parallel Trends" Review of Economic Studies.
    - Roth, Sant’Anna, Bilinksky, & Poe (2023). "“What’s trending in difference-in-differences? A synthesis of the recent econometrics literature”. Journal of Econometrics"
    - Agarwal & Alam  (2025), "The Unintended Benefits of Women Empowerment on Household Sanitation"
    <!-- - Cengiz, D., Dube, A., Lindner, A., & Zipperer, B. (2019). "The effect of minimum wages on low-wage jobs: Evidence from the United States using a bunching estimator." Quarterly Journal of Economics. -->

- **Shrinkage Estimators**
    - Walters  (2024), "Empirical Bayes methods in labor economics," Handbook of Econometrics, Volume 5.
    - Kline  & Walters (2021), "Reasonable Doubt: Experimental Detection of Job-Level Employment Discrimination," Econometrica
    - Alam, Mookerjee & Roy (2021) "Employee-Side DIscrimination--Beliefs and Preferences"
    - Alam, Davis & Gregory (2025) "Optimal Place Based Redistribution using Geographic Variation in the Marginal Utility of Income"

- **Leniency IV Designs**
    - Dobbie,  Goldin,  & Yang (2018). "The Effects of Pretrial Detention on Conviction, Future Crime, and Employment: Evidence from Randomly Assigned Judges" American Economic Review.
    - Dobbie, Goldsmith-Pinkham, & Yang (2017). "Consumer Bankruptcy and Financial Health" Review of Economics and Statistics.
    - Frandsen, Lefgren, &  Leslie (2023). "Judging Judge Fixed Effects." American Economic Review.
    - Hull, Goldsmith-Pinkham & Kolesár (2025) "Leniency Designs: An Operator's Manual"

- **Shift share IV**
    - Borusyak, Hull, & Jaravel (2022). "Quasi-experimental shift-share research designs." Review of Economic Studies.
    - Goldsmith-Pinkham, Sorkin, & Swift (2020). "Bartik instruments: What, when, why, and how." American Economic Review.
    - Borusyak, Hull & Jaravel (2025), "A Practical Guide to Shift-Share Instruments" Journal of Economic Perspectives.

- **Marginal Treatment Effects**
    - Heckman, & Vytlacil (2007). "Econometric evaluation of social programs, part I: Causal models, structural models and econometric policy evaluation." Handbook of Econometrics.
    - Heckman, & Vytlacil (2007). "Econometric evaluation of social programs, part II: Using the marginal treatment effect to organize alternative econometric estimators to evaluate social programs." Handbook of Econometrics.


Some additional useful references for some topics are:

- Angrist and Pischke (2009), *Mostly Harmless Econometrics: An Empiricist's Companion*. Princeton University Press.
- Cunningham, S (2012), *Causal Inference: The Mixtape*. Yale University Press. [[Open-source Link]](https://mixtape.scunning.com/)

## Assessment

- **Problem Sets — 80%:** Four problem sets involving both theoretical derivations and empirical exercises + presentations. These are to be completed in groups of two.
    - Students can use their programming language of choice. I recommend R.
    - Students are expected to compile their assignments using LaTeX or equivalently in R Markdown. The final submission will involve both code and results in a single PDF with all tables properly formatted, variables properly labeled, and figures and tables with complete footnotes as if they are submitting the work to a journal.
    - I will also assign students topics for presentations/referee reports. 
- **Class  participation — 20%**
