---
title: "PhD: Structural + Computation"
author: "Moshi Alam"
date: "2025"
format:
  html:
    toc: true
    toc-depth: 3
  #pdf:
    #toc: true
    #documentclass: article
---

## Course Description

THis si the second part of a two-part sequence of Applied ecopnometrics at the PhD level. Here I cover structural models and econometric methods with a focus on some types of labor and public economics problems. Having a comprehensive course on structural models is nearly impossible since  structural work fine tune the model to the specific theory and context. The key lies in identification, which can ultimatley help us in doing counterfactuals. Hence, my emphasis will be mostly on identification, and primarily with discrete choice models (both static and dynamic) using estimation methods like MLE, GMM, SMM, and primarily indirect inference. I will cover some numerical optimization methods like gradient-based, derivative-free methods but mostly Nelder-Mead simplex algorithm. 

I do not find the discussions of whether structural models are better than design-based (reduced form) methods very constructive and hence will not engage in them. However, I will list some papers that discuss these. I like both, and have found both helpful in my work. In my view, both approaches have their own strengths, and it is cool to leverage best of both worlds.

No textbook as such---its mostly papers, but I found [Kenneth Train's *Discrete Choice Methods with Simulation*](https://eml.berkeley.edu/books/choice2.html) very helpful when I was learning discrete choice models for the first time. Depending on time I will also talk about some of my experience in improving computational efficiency in `julia`, and discuss some of the workflows that have worked for me.



## Assessment

- **Problem Sets — 80%:** Four problem sets + presentations. These are to be completed in groups of two.
    - Students can use their programming language of choice. I recommend `julia`, because of its computational advantages. However, `R` or `Python` are also fine.
    - Students are expected to compile their assignments using LaTeX. The final submission will involve both code and results in a single PDF with all tables properly formatted, variables properly labeled, and figures and tables with complete footnotes as if they are submitting the work to a journal.
    - I will also assign students topics for presentations/referee reports. 
- **Class attendance and participation — 20%**

##  Readings

The readings are in not a particular order, although I will talk about identification in general first and then how is strucutral (model-based) approach different from reduced form (design-based) approach. Things that are not in particular order maybe specific topics & estimation routines and papers applying them.

### Identification

- [Heckman, J.J. and Vytlacil, E.J. (2007a)](https://www.sciencedirect.com/science/article/abs/pii/S1573441207060709). "Econometric Evaluation of Social Programs, Part I: Causal Models, Structural Models and Econometric Policy Evaluation." *Handbook of Econometrics*, Vol. 6B, Ch. 70.

- [Heckman, J.J. and Vytlacil, E.J. (2007b).](https://www.sciencedirect.com/science/article/abs/pii/S1573441207060710) "Econometric Evaluation of Social Programs, Part II: Using the Marginal Treatment Effect to Organize Alternative Econometric Estimators to Evaluate Social Programs, and to Forecast their Effects in New Environments." *Handbook of Econometrics*, Vol. 6B, Ch. 71.

- [French, E. and Taber, C. (2011).](https://www.sciencedirect.com/science/article/abs/pii/S0169721811004126) "Identification of Models of the Labor Market." *Handbook of Labor Economics*, Vol. 4A, Ch. 6: 537-617.

- [Matzkin, R.L. (2007).](https://www.sciencedirect.com/science/article/abs/pii/S1573441207060734) "Nonparametric Identification." *Handbook of Econometrics*, Vol. 6B, Ch. 73.

### Structural vs. Reduced Form Methods

- [Low, H. and Meghir, C. (2017)](https://www.aeaweb.org/articles?id=10.1257/jep.31.2.33). "The Use of Structural Models in Econometrics." *Journal of Economic Perspectives*, 31(2): 33-58.

- [Angrist, J.D. and Pischke, J.S. (2010).](https://www.aeaweb.org/articles?id=10.1257/jep.24.2.3) "The Credibility Revolution in Empirical Economics: How Better Research Design is Taking the Con out of Econometrics." *Journal of Economic Perspectives*, 23(1): 69-90.

- [Keane, M.P. (2010).](https://www.aeaweb.org/articles?id=10.1257/jep.24.2.47) "A Structural Perspective on the Experimentalist School of Econometrics." *Journal of Economic Perspectives*

- [Galiani, S. and Pantano, J. (2021)](https://www.nber.org/papers/w28698). "Structural Models: Inception and Frontier." NBER Working Paper 28698.

<!-- - Heckman, J.J. and Urzúa, S. (2010). "Comparing IV with Structural Models: What Simple IV Can and Cannot Identify." *Journal of Econometrics*, 156(1): 27-37. -->


<!-- - Reiss, P.C. and Wolak, F.A. (2007). "Structural Econometric Modeling: Rationales and Examples from Industrial Organization." *Handbook of Econometrics*, Vol. 6A, Ch. 64. -->

### Static Discrete Choice Models

- McFadden, D. (1973). "Conditional Logit Analysis of Qualitative Choice Behavior." In P. Zarembka (ed.), *Frontiers in Econometrics*. Academic Press.

- McFadden, D. (1981). "Econometric Models of Probabilistic Choice." In C. Manski & D. McFadden (eds.), *Structural Analysis of Discrete Data*.

<!-- - Train, K. (2009). *Discrete Choice Methods with Simulation*. Cambridge University Press. [Selected chapters] -->

<!-- ### Identification in Discrete Choice

- Manski, C.F. (1975). "Maximum Score Estimation of the Stochastic Utility Model of Choice." *Journal of Econometrics*, 3(3): 205-228.

- Lewbel, A. (2000). "Semiparametric Qualitative Response Model Estimation with Unknown Heteroscedasticity or Instrumental Variables." *Journal of Econometrics*, 97(1): 145-177. -->

###  Dynamic  Discrete Choice Models

- Rust, J. (1987). "Optimal Replacement of GMC Bus Engines: An Empirical Model of Harold Zurcher." *Econometrica*, 55(5): 999-1033.

- Hotz, V.J. and Miller, R.A. (1993). "Conditional Choice Probabilities and the Estimation of Dynamic Models." *Review of Economic Studies*, 60(3): 497-529.

<!-- - Hotz, V.J., Miller, R.A., Sanders, S., and Smith, J. (1994). "A Simulation Estimator for Dynamic Models of Discrete Choice." *Review of Economic Studies*, 61(2): 265-289. -->

<!-- - Aguirregabiria, V. and Mira, P. (2002). "Swapping the Nested Fixed Point Algorithm: A Class of Estimators for Discrete Markov Decision Models." *Econometrica*, 70(4): 1519-1543. -->

- Arcidiacono, P. and Miller, R.A. (2011). "Conditional Choice Probabilities and the Estimation of Dynamic Models with Unobserved Heterogeneity." *Econometrica*, 79(6): 1823-1867.

###  Estimation Methods

#### Maximum Likelihood Estimation

- Ruud, P.A. (1991). "Extensions of Estimation Methods Using the EM Algorithm." *Journal of Econometrics*, 49(3): 305-341.

- Keane, M.P. and Wolpin, K.I. (1994). "The Solution and Estimation of Discrete Choice Dynamic Programming Models by Simulation and Interpolation: Monte Carlo Evidence." *Review of Economics and Statistics*, 76(4): 648-672.

#### Generalized Method of Moments

- Hansen, L.P. (1982). "Large Sample Properties of Generalized Method of Moments Estimators." *Econometrica*, 50(4): 1029-1054.

<!-- - Newey, W.K. and McFadden, D. (1994). "Large Sample Estimation and Hypothesis Testing." *Handbook of Econometrics*, Vol. 4, Ch. 36. -->

#### Simulated Method of Moments

- McFadden, D. (1989). "A Method of Simulated Moments for Estimation of Discrete Response Models without Numerical Integration." *Econometrica*, 57(5): 995-1026.

<!-- - Pakes, A. and Pollard, D. (1989). "Simulation and the Asymptotics of Optimization Estimators." *Econometrica*, 57(5): 1027-1057. -->

#### Indirect Inference

- Gourieroux, C., Monfort, A., and Renault, E. (1993). "Indirect Inference." *Journal of Applied Econometrics*, 8(S1): S85-S118.


###  Applications in Labor Economics

<!-- ### Early Childhood and Education

- Heckman, J.J. and Zhou, J. (2025). "A Study of the Microdynamics of Early Childhood Learning." NBER Working Paper 34294.

- Cunha, F., Hu, Q., Salvati, A., Wolpin, K., and Zeng, R. (2025). "An Evaluation of the Alief Independent School District Jumpstart Program: Using a Model to Recover Mechanisms from an RCT." NBER Working Paper 33537. -->

#### Stated Preferences

- Wiswall, M. and Zafar, B. (2018). "Preference for the Workplace, Investment in Human Capital, and Gender." *Quarterly Journal of Economics*, 133(1): 457-507.

- *Alam, M.M.U., Mookerjee, M., and Roy, S. (2021) "Employee-Side Discrimination: Beliefs and Preferences."*

- Adams, A., and Andrew, A. (2025) "Revealed Beliefs and the Marriage Market Return to Education“ *Quarterly Journal of Economics*.

- Delavande, A. and Zafar, B. (2019). "University Choice: The Role of Expected Earnings, Nonpecuniary Outcomes, and Financial Constraints." *Journal of Political Economy*, 127(5): 2343-2393.

<!-- - Abaluck, J. and Adams-Prassl, A. (2021). "What Do Consumers Consider Before They Choose? Identification from Asymmetric Demand Responses." *Quarterly Journal of Economics*, 136(3): 1611-1663. -->

#### Monopsony and Firm Effects

- Card, D., Cardoso, A.R., Heining, J., and Kline, P. (2018). "Firms and Labor Market Inequality: Evidence and Some Theory." *Journal of Labor Economics*, 36(S1): S13-S70.

<!-- - Card, D., Cardoso, A.R., and Kline, P. (2016). "Bargaining, Sorting, and the Gender Wage Gap: Quantifying the Impact of Firms on the Relative Pay of Women." *Quarterly Journal of Economics*, 131(2): 633-686. -->

- Lamadon, T., Mogstad, M., and Setzler, B. (2022). "Imperfect Competition, Compensating Differentials, and Rent Sharing in the US Labor Market." *American Economic Review*, 112(1): 169-212.

- Kroft, K., Luo, Y., Mogstad, M., and Setzler, B. (2025). "Imperfect Competition and Rents in Labor and Product Markets: The Case of the Construction Industry." *American Economic Review*, 115(9): 2926-2969.

- Kline, P. and Petkova, K. (2025). "Labor Market Monopsony: Fundamentals and Frontiers." *Handbook of Labor Economics*, Vol. 6: 655-728.


#### Empirical school choice

- Agarwal, N., & Somaini, P. (2018). "Demand Analysis Using Strategic Reports: An Application to a School Choice Mechanism." Econometrica

- Chade, H., Lewis, G., & Smith, L. (2014). "Student Portfolios and the College Admissions Problem." Review of Economic Studies 

- Kapor, A., Neilson, C., & Zimmerman, S. (2020). "Heterogeneous Beliefs and School Choice Mechanisms." American Economic Review


#### Career Decisions, Human Capital, Household consumption, Migration, Search

- [Postel-Vinay, F. and Robin, J.M. (2002)](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1468-0262.2002.00441.x). "Equilibrium Wage Dispersion with Worker and Employer Heterogeneity." *Econometrica*, 70(6): 2295-2350.

- Keane, M.P. and Wolpin, K.I. (1997). "The Career Decisions of Young Men." *Journal of Political Economy*, 105(3): 473-522.

- Eckstein, Z. and Wolpin, K.I. (1989). "Dynamic Labour Force Participation of Married Women and Endogenous Work Experience." *Review of Economic Studies*, 56(3): 375-390.

- [Todd, P.E. and Wolpin, K.I. (2006)](https://www.aeaweb.org/articles?id=10.1257/aer.96.5.1384). "Assessing the Impact of a School Subsidy Program in Mexico: Using a Social Experiment to Validate a Dynamic Behavioral Model of Child Schooling and Fertility." *American Economic Review*, 96(5): 1384-1417.

- [Voena, A. (2015)](https://www.aeaweb.org/articles?id=10.1257/aer.20120234). "Yours, Mine, and Ours: Do Divorce Laws Affect the Intertemporal Behavior of Married Couples?" *American Economic Review*, 105(8): 2295-2332.

- [Kennan, J. and Walker, J.R. (2011).](https://onlinelibrary.wiley.com/doi/abs/10.3982/ECTA4657) "The Effect of Expected Income on Individual Migration Decisions." *Econometrica*, 79(1): 211-251.



### Applications in Public Economics

- *Alam, M.M.U., Davis, M, and Gregory, J. (2025). "Optimal Place-Based Redistribtuion using Geographic Variation in Marginal Utility of Income"*

- Chetty, R. (2009). "Sufficient Statistics for Welfare Analysis: A Bridge Between Structural and Reduced-Form Methods." *Annual Review of Economics*, 1: 451-488.

### Applications in Development Economics

- Attanasio, O., Meghir, C., and Santiago, A. (2012). "Education Choices in Mexico: Using a Structural Model and a Randomized Experiment to Evaluate PROGRESA." *Review of Economic Studies*, 79(1): 37-66.

- Duflo, E., Hanna, R., and Ryan, S.P. (2012). "Incentives Work: Getting Teachers to Come to School." *American Economic Review*, 102(4): 1241-1278.

### Survey Articles

- Todd, P.E. and Wolpin, K.I. (2010). "Structural Estimation and Policy Evaluation in Developing Countries." *Annual Review of Economics*, 2: 21-50.

- Keane, M.P., Todd, P.E., and Wolpin, K.I. (2011). "The Structural Estimation of Behavioral Models: Discrete Choice Dynamic Programming Methods and Applications." *Handbook of Labor Economics*, Vol. 4, Ch. 4: 331-461.

- Aguirregabiria, V. and Mira, P. (2010). "Dynamic Discrete Choice Structural Models: A Survey." *Journal of Econometrics*, 156(1): 38-67.

- Keane, M.P. and Wolpin, K.I. (2009). "Empirical Applications of Discrete Choice Dynamic Programming Models." *Review of Economic Dynamics*, 12(1): 1-22.

- Blundell, R. and MaCurdy, T. (1999). "Labor Supply: A Review of Alternative Approaches." *Handbook of Labor Economics*, Vol. 3A, Ch. 27.
