---
title: "Econometrics PS 5"
author: "Prof Alam"
format: html
editor: visual
theme: flatly
toc: true
code-fold: false
---

## Simple 2x2 DiD

Use the .Rmd file that we used in class to load the cleaned Card and Krueger (1994) dataset from github remotes, and assign it to an object called `ckdata`. Load other associated libraries as needed. Prepare the data for estimation of the impact of the minimum wage increase policy on employment as we did in class. 

IMPORTANT: In all estimations, whenever you are interpreting your estimates, state all necessary assumptions for you to claim that the estimated effect is causal (i.e. identification assumptions).

### Question 1

Plot the data of starting wages by the state and the year (before and after the minimum wage increase). Comment on any patterns you observe.

### Question 2

- Re-estimate the simple 2x2 DiD model of the effect of minimum wage increase on employment that we did in class. Report and interpret the results. 
- How many unique food chains are in the data? 
- Estimate the simple 2x2 DiD model of the effect of minimum wage increase on employment with `chain` fixed effects. Report, compare and interpret the results.

### Question 3

- What are some additional control variables that you can add to the model? Re-estimate the DiD model with these additional controls. Report, compare and interpret the results. (Hint: Be mindful of the discussion of "bad controls" we discussed before the mid-term in class.)

### Question 4

- Did employers in NJ pass on the increased labor costs to consumers in the form of higher prices? Answer this question empirically. 

## 2xT Event Study

The .Rmd notebook I uploded on canvas where we worked on such problems will be a helpful reference for this part of the problem set.

Use the data `2xT_did_ps5data.csv` provided on Canvas for this part of the problem set. This dataset contains data from 2000 to 2004 on firm id, firm profits, treatment status, and other firm characteristics. 

In 2002, a government introduces a profit tax credit to encourage small manufacturing firms to upgrade to more energy-efficient machinery. Because of budget and administrative constraints, the program is offered first to firms that already have relatively high electricity usage per unit of output. Firms with lower electricity intensity are not initially eligible and thus do not adopt the program during the sample period. On average, profits increase over time in both treated and control firms, reflecting improving economic conditions that affect all firms. But we are interested in estimating the causal effect of the energy-efficiency program on firm profits.

The treated group ($D_i = 1$) consists of firms that adopt the energy-efficiency program in 2002, and the control group consists of otherwise similar firms that never become eligible in this window. The outcome $Y_{it}$ is each firm’s monthly profit measured in hundreds of thousands of dollars. 

- Load the data into R and create a variable `t` that indicates the number of years since treatment.  This is similar to what we worked on in class.
- Create a variable `post` that is equal to 1 if the observation is in the post-treatment period and 0 otherwise.
- Estimate a simple 2xT DiD model of the effect of the policy on profits controlling for firm age in your estimating and industry fixed effects. Write the estimating equation. Estimate it on R and report and interpret the results. What assumptions are you making to interpret the estimates causally?
- Now I want you to estimate an event study model of the effect of the policy on profits controlling for firm age in your estimating and industry fixed effects. Write the estimating equation. Estimate it on R and report and interpret the results. What assumptions are you making to interpret the estimates causally? Hint: You will need to create event time dummies for this, similar to what we did in class.

- What do the pre-treatment coefficients tell you about your main identification assumption?

### Bonus not to be turned in

- Plot the event study coefficients with 95% confidence intervals. Interpret the plot.

